source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’10.0’

use_frameworks!

target 'HSE Staff' do
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'SwiftHash', git: 'https://github.com/onmyway133/SwiftHash'
end
